apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service-container
        image: mukeshkannam/service:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000




